### ISSUE TITLE
Publishing venture: "How did you start coding"

### ISSUE THREAD

**Issue by ghost** [rachsmithcodes/ama#11]
Hello Rachel,

My name is Alex and I used to run the Pastry Box Project: https://the-pastry-box-project.net/

The Pastry Box is collaborative blog which has published one text everyday since January 1st 2012. We closed on December 31st, after four years of hard work.

I've launched a new publishing project. It's called "How did you start coding?". 

https://superyesmore.com/publication/how-did-you-start-coding-486219196f7a99515f31f5edbce83841

It's all in the title. I'm going to ask bright minds to share with the world how they started coding. One text will be published every week throughout 2016.

Would you be interested in contributing a piece to the project?

All the best.

Alex
@alexduloz

**Comment by rachsmithcodes** [comment]
hey @alexduloz, I would definitely love to contribute, how do I go about doing that? You can email me deets if you like - contact at rachsmith dot com

**Comment by ghost** [comment]
Hello. I sent you an email.

:)
