### ISSUE TITLE
the Animated Background Header have a bug!

### ISSUE THREAD

**Issue by CrazyBay** [rachsmithcodes/ama#13]
When I use a small browser window open demo-01,animation will become intensive.But when the window to maximize the size of canvas to adjust,and the area of particle animations will not change.its area is the size of a small window.

**Comment by rachsmithcodes** [comment]
hi,

The code for the Codrops animated background headers was just an experimental demo and not meant to cover for every possible scenario / device. The idea is that you take that code and modify it to fit your own needs.
