### ISSUE TITLE
What technology are you most excited about at the moment?

### ISSUE THREAD

**Issue by RyKilleen** [rachsmithcodes/ama#18]
Hey Rachel,

Thanks for setting this up! Great to have all the answers in public like this. 

I was curious what has you most excited at the moment, from progress in Web GL to who knows what.

**Comment by rachsmithcodes** [comment]
Hi Ryan!

I'm excited about a lot of things!!!!!! Every day I have to pinch myself when I think about the fact I get to work in such an amazing field! A compacted list:
1. WebVR and the potential for us to create experiences with native-like rendering with headless browsers.
2. Building interfaces with web code that mesh with physical installations (eg https://googlecreativelab.github.io/anypixel/)
3. Advancements in web animation authoring in the browser with the Web Animations API and countless new animation libraries being built and iterated on.
4. The fact that more and more creative people from other design disciplines are learning JavaScript and bringing their influence to the platform. This emerging discipline of web technology art and art generated by code.
5. JavaScript!!!!!! Where the language is heading (I'm really enjoying es2015 right now), the fact it is so accessible and is becoming a language to drive everything from VR to IoT.

✨ 💯 ✨ 💯 ✨ 💯 ✨ 💯  It's all coming up ~~milhouse~~ web devs!!! ✨ 💯 ✨ 💯 ✨ 💯 ✨ 💯 

Thanks for your question, what are you excited about?
