### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by ismaelhaider** [rachsmithcodes/ama#21]
Hi,

I am your big fan on web, I need to see the animated Header for america which you posted on codepen.Can you please share the code,so I can edit for my demo.

Thanks

**Comment by rachsmithcodes** [comment]
hi @ismaelhaider the pen code is here http://codepen.io/rachsmith/pen/c0dfaf2e3e570ebfd7c9d65430e80376/

its a fork of this pen
http://codepen.io/judag/details/XmXMOL#forks

**Comment by ismaelhaider** [comment]
Thank you so much, When I see your work, Really I want to be a developer like you. Amazing work.I wish If I can meet you in my life. 

Thanks Again
Ismail

**Comment by ismaelhaider** [comment]
Bythe Way,this animated gif, Cant we get source file for this ? Actuallay i want to write "Qatar333"

**Comment by rachsmithcodes** [comment]
its just a gif I found on the internet :) so don't have the source sorry!
