### ISSUE TITLE
CodePen LA Meetup

### ISSUE THREAD

**Issue by rouzbeh84** [rachsmithcodes/ama#23]
A dashing gentleman named Chris suggested I reach out and see if you would be gracious enough to do a lightning talk at an upcoming meetup we're having :). Please let me know if this is possible as we would absolutely love to have you!

[Meetup Link](https://www.meetup.com/LearnToCodeLA/events/233257594/)
[Codepen Link](https://blog.codepen.io/meetups/)

**Comment by rachsmithcodes** [comment]
heya Rouzbeh sure thing, whats a good contact email so I can shoot you some Q's?

**Comment by rouzbeh84** [comment]
Awesome! My email is rouzbeh.sarrafieh@gmail.com. Thanks so much 😸
