### ISSUE TITLE
Your four stages of animation

### ISSUE THREAD

**Issue by mmullen200** [rachsmithcodes/ama#25]
Last night at the meetup in L.A., you talked about the four stages you go through when you're creating animations. Have you written about that in one of your blog posts or elsewhere? I'd like to learn more about the process you were talking about... I wasn't quick enough to take notes.

**Comment by rachsmithcodes** [comment]
hi Michael,

Here's a copy of the slides I had with the four steps. https://speakerdeck.com/rachsmith/codepen-la-lightning-preso-sept-2016 I will turn this in to a blog post this weekend hopefully so I'll have a written version of the talk out soon. Thanks for coming!

**Comment by mmullen200** [comment]
Thanks for the slides, excited to read the blog post. I'm a big fan of
Three.js, nice to see how you're using it in your projects.
