### ISSUE TITLE
Guest speaking for high school programming students?

### ISSUE THREAD

**Issue by bdacoscos** [rachsmithcodes/ama#27]
Hi Rachel!

I met you in September at the Web Dev Show & Tell mixer held at NationBuilder and have been meaning to get in touch with you sooner. I have a group of high school programmers that I think would be interested in hearing you talk about your work with CodePen and your journey getting there. 

Would you be interested in coming by to speak to our students? We would be thrilled to arrange something with you if you were up to it!

Thanks,
Briana Dacoscos

P.S. We are based in Pasadena!

**Comment by rachsmithcodes** [comment]
Hi Briana, do you an email address I can contact you on about this? Thanks!

**Comment by bdacoscos** [comment]
Certainly! Here's my work email: bdacoscos@pasedfoundation.org 

Also here's a link to our website for more info about our program: www.theappacademy.us. Thanks!!
