### ISSUE TITLE
SharkByte - boo ha ha

### ISSUE THREAD

**Issue by Brikky** [rachsmithcodes/ama#28]
Hi Rach!

I just wrapped up a 12 week coding bootcamp in SF, and my final project is something similar to CodePen.

I was wondering if you had any free time if you could check it out and offer some feedback! 
(I have no intent or desire to pursue this project as anything beyond a learning experience/portfolio piece, but understand if you're bound by some sort of non-compete or contract clause that prevents this.)

One of the main features of my web app is real-time collaboration, and I was wondering if you and the other engineers at CodePen have ever discussed adding that as a feature. I dug around on CodePen's website, and I wasn't able to find anything mentioning jobs (at CodePen, anyway) and it seems like you guys are a really small team (approachable!) so I thought it would be cool to reach out directly.

The app is hosted on Heroku at: 
https://sharkbyte.herokuapp.com/

And the demo login is
**User:** admin
**Pass:** password

**Comment by rachsmithcodes** [comment]
Hi Brandon,

Sorry it took a little while to get back to you. That is a cool project and definitely not an easy thing to put together! Is there anything specific you want feedback on? (a tip I have for you after some experience - when asking for feedback, the more specific the request the more likely you will get a response :))

We actually offer a real-time collab mode for Pro accounts https://blog.codepen.io/documentation/pro-features/collab-mode/ one thing we need to work on is making those sorts of features more discoverable!

You're right, CodePen is a small team and there are no plans to expand or hire again for the near future, we're just trying to get ourselves back to profitability first after accepting some funding recently. Keep up the good work and I'm sure you'll find a job at a great company that utilizes your skills!

Rach
