### ISSUE TITLE
[Egoistic question] Is this enough to get a job in LA or NY?

### ISSUE THREAD

**Issue by lightest** [rachsmithcodes/ama#3]
Hey Reachel!
I'm thinking seriously on moving to US next year. Since you've moved to LA yourself can I have your opinion on my work? Basically here is what I can: http://agafnik.com/testchambers/ what chances do I have?

Thanks in advance!

**Comment by rachsmithcodes** [comment]
Heya @lightest 
That is some nice stuff, clearly you know what you're doing with Canvas.
As far as getting a job in the USA goes, there are a number of things that come in to play besides coding skills. Namely, your previous work experience and how you've applied those code skills to commercial use. Generally, people with creative coding skills like yours move in to somewhere in the digital advertising field as that's where the demand for that sort of work is. Based on my personal experience, the main thing agencies are looking for when they hire people is examples of previous work experience in a similar work environment - <a href="http://rachsmith.com/2015/portfolio-tips">I wrote more about this here</a>. 
I worked for a number of agencies in the UK and Australia before being offered my USA job. It was that work experience combined with my JavaScript skills and interest in creative coding that scored me a great job here. I hope this info helps you some, and good luck chasing the job opportunities and career you want for yourself!
