### ISSUE TITLE
Hey, Rachel!

### ISSUE THREAD

**Issue by ghost** [rachsmithcodes/ama#30]
Hey, Rachel! I'm a big fan. I have a tiny podcast where I talk to amazing peeps about how they got to where they are now, what their day-to-day life is like, and what their habits are. Also we just talk about life and not take things seriously. :)

I have two episodes so far at https://soundcloud.com/friendstalkfrontend if you want to get a feel for it.

So! I was wondering: would you be down to be interviewed for an hour? I think peeps will learn a lot from you esp since you talk about things like https://rachsmith.com/2016/career-fomo and https://rachsmith.com/2016/agency-to-remote-1-year-later <3

![](https://cloud.githubusercontent.com/assets/81969/21966366/b4542862-db3f-11e6-8a7e-44aaaa9a7538.gif)

Thank you so much for reading!

**Comment by rachsmithcodes** [comment]
Hi Jag, nice to make your web acquaintance! I would be very happy to be interviewed, send me an email at contact@rachsmith.com with your preferred recording time/s and we'll figure something out :)
