### ISSUE TITLE
[codepen] I forked you project and try to do some improve :D!

### ISSUE THREAD

**Issue by lichin-lin** [rachsmithcodes/ama#31]
Hello, my name is Lichin.
recently I saw the spin color stroke project on codepen,
and I try to do some change on it: http://codepen.io/lichin-lin/details/NdpaLa/ (i really like it haha!)
I am here to ask if it`s okay to use your javascript code in anywhere (animation part) ?
or I need to write my own code :D !
anyway, this is really a beautiful js practice!!!

**Comment by rachsmithcodes** [comment]
Hi Lichin,

That's a really cool fork of the pen! Well done. All of my CodePens are open source so feel free to use any of the code however you wish.
Thanks for the compliment, I wish you well in your coding journey!
