### ISSUE TITLE
Are you interested in speaking at React Rally?

### ISSUE THREAD

**Issue by jergason** [rachsmithcodes/ama#32]
Hey Rachel. @sdras (who spoke at React Rally last year and did a killer job) recommended you as someone rad doing rad React things at CodePen. Are you interested in speaking this year? If so, what is a good way to follow up? (http://reactrally.com and http://speak.reactrally.com has some details)

**Comment by rachsmithcodes** [comment]
Hi Jamison!
Thanks for reaching out, it was so nice of Sarah to recommend me but I'm taking a break from conference speaking during 2017. Best of luck with React Rally!
