### ISSUE TITLE
Animated Background Headers 

### ISSUE THREAD

**Issue by ghost** [rachsmithcodes/ama#33]
Hello, I saw your example of animation, and I wanna to understand how you create just the line and point of first animation because I wanna to learn canvas animation.

https://tympanus.net/codrops/2014/09/23/animated-background-headers/

**Comment by rachsmithcodes** [comment]
Hi gisesonia,

The lines are drawn using lineTo https://www.w3schools.com/tags/canvas_lineto.asp and the points (circles) are drawn using arc https://www.w3schools.com/tags/canvas_arc.asp. I wrote a little tutorial on how to get started with canvas animations https://codepen.io/rachsmith/post/controlling-the-canvas-with-javascript-objects.
Cheers!
