### ISSUE TITLE
LISK platform

### ISSUE THREAD

**Issue by omtamal** [rachsmithcodes/ama#38]
Hi Rachel,
as you are an expert on JS, I was wondering if you are familiar with JS implementation to blockchains – what does it mean that you can build a JavaScript app on top of blockchain, more precise on top of LISK platform? Is LISK like React? Uhh :-)
Here is a LISK diagram that helps little: https://imgur.com/a/dc6ZA

Happy New Year and thank you for your time,
Tadej

**Comment by rachsmithcodes** [comment]
Hi Tadej,

I haven't really looked in to LISK or things like it. I don't know enough about the block chain to really provide insight, I would have to learn about that first and so far haven't felt the need. You asked this question ages ago (sorry) so perhaps you have learnt more about it yourself :) 

Cheers
