### ISSUE TITLE
Working for US company as an Australian resident

### ISSUE THREAD

**Issue by evmcl** [rachsmithcodes/ama#40]
Hi Rachel,

Recently listened to you on [this podcast](http://developeronfire.com/podcast/episode-288-rachel-smith-connecting-and-delivering), and was wondering if you are setup directly as an employee of CodePen US, or you have your own Company, and if there are any gotchas related to tax and benefits (e.g., superannuation, leave and such) that you have to watch out for.

Thanks.

E.

**Comment by rachsmithcodes** [comment]
hi Evan,

I'm happy to answer this one but would prefer to do it over email. Feel free to email me at contact@rachsmith.com so we can discuss :)

Cheers!
