### ISSUE TITLE
Paid Tutoring

### ISSUE THREAD

**Issue by godiaz** [rachsmithcodes/ama#44]
Hey Rachel, 

I've been seeing some of your code pens (amazing) and i was wondering if you do online JS tutoring?
I am trying to master some of my skills.

Thanks,
Gonzalo

**Comment by hedgerh** [comment]
@godiaz saw you hadnt received a reply.  what kind of tutoring were you looking for?

**Comment by rachsmithcodes** [comment]
Hi Gonzalo,
I apologise for my late reply, I have somewhat neglected this repo of late. I do not offer any tutoring at this time, my hands are pretty full at the moment between my day job and my family. Best of luck with your coding journey!
