### ISSUE TITLE
What is a Web Janitor?

### ISSUE THREAD

**Issue by cliff76** [rachsmithcodes/ama#6]
Your Twitter page uses an interesting title describing you as a "Web Janitor". Does that mean you are skilled in HTML bleach, CSS Lysol, and can get Javascript stains out of those hard to reach places?

**Comment by rachsmithcodes** [comment]
haha @cliff76 
I actually first heard <a href="https://twitter.com/davatron5000">Dave Rupert</a> use the word "web janitor" to describe the sort of work a lot of us Front End Developers do. Often we're not just building sites, we're maintaining and fixing the work other people have written, trying to deal with cross browser compatability problems. I thought this was a great description of the majority of work I was doing for Active Theory, hence adopting the title of web janitor :smile:
